name = "HTTP Server"
language = "rust"
version = "0.24.0"
type = "provider"
wit = "../../../crates/provider-http-server/wit"

[rust]
target_dir = "../../../"

[provider]
bin_name = "http-server-provider"
vendor = "wasmCloud"
